#-- list of packages (or group of packages) to compile for this experiment:
oceanic # this pkg_group will include the packages "gfd, gmredi, kpp" (see MITgcm/pkg/pkg_groups)
cd_code # applies a gentle velocity-smoothing filter each timestep to prevent numerical oscillations in the ocean flow
exf     # external forcing package for applying time-varying surface fluxes (wind stress, heat, moisture, radiation, pressure) with optional bulk-formula physics.
#seaice
#salt_plume
#ptracers
longstep
diagnostics
#timeave
#mnc # dumps output in netCDF format
tapenade
adjoint # this pkg_group will include the packages "autodiff, ctrl, cost, grdchk"
