#-- Packages compiled into the DINO_1deg forward model; see README.md.

#gfd
#-mom_fluxform
exch2
mom_vecinv
diagnostics
generic_advdiff
monitor
#mnc

#cal
#exf
gmredi
kpp
#seaice
#salt_plume
#obcs
#down_slope

#debug
#autodiff
#cost
#ctrl
#grdchk
#ecco
#smooth
#profiles
rw
mdsio
cd_code # applies a gentle velocity-smoothing filter each timestep to prevent numerical oscillations in the ocean flow
