#!/bin/bash
# Build the Tapenade ADJOINT with EVERY call checkpointed (Tapenade's default).
#   sources : code_tap/ + input_tap/  ->  build_tapAdj_ckpAll/mitgcmuv_tap_adj
#
# This is the REFERENCE adjoint, not the default one. Since 2026-09-02 the
# default (what ./scripts/build_tapAdj.sh, a symlink, runs) is
# build_tapAdj_nocheckpoint.sh: the same adjoint with the profile-guided
# -nocheckpoint list added, bitwise identical in fc, adxx_* and ADJ* at 30 d
# and 5 yr, and 1.5x faster. Until that day this script WAS build_tapAdj.sh,
# so every run directory named tapAdj_ckpAll_* (and, before the 2026-09-02
# scratch rename, plain tapAdj_*) up to job 31055 came from it.
#
# Keep it for what -nocheckpoint cannot do: it is what the profiler build
# (build_tapAdj_profile.sh) measures, since a profile of the tuned build
# would only show the residual; it is the fallback when a configuration change
# invalidates the routine list; and it is the baseline for timing comparisons.
# It is no longer needed as a correctness control -- the tuned build is
# bitwise identical to it.
#
# Uses STOCK genmake2: the ADJ* dump hook is generated by Tapenade itself,
# because code_tap/forward_step.F passes the state fields to
# DUMMY_IN_STEPPING (under ALLOW_TAPENADE) and code_tap/flow_tap_local
# declares them active. That library reaches Tapenade through the setup's
# -adof file, code_tap/adjoint_tap_local, which sources the stock options
# and appends it AFTER the stock flow_tap (Tapenade keeps the last
# declaration of an external). No generated file is post-edited; the only
# DINO-specific Tapenade inputs are that library and options file.
#
# This file says WHAT to build; HOW is tools/lib/build_body.sh, shared by
# every build script (machine profile, genmake2, make, the generated-hook
# assertions listed in setup_params.sh, build_info.txt). Run from the setup
# directory: ./scripts/build_tapAdj_ckpAll.sh
# Pair with submit_tapAdj_ckpAll.sh.

set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BUILD_DIR=build_tapAdj_ckpAll
BUILD_MODE=tapAdj
PARALLEL=mpi
MODS=(../code_tap)
TAP_EXTRA=""
CKP=ckpAll;     CKP_NOTE="every call inside a step checkpointed (Tapenade default)"
VARIANT=plain;  VARIANT_NOTE="code_tap/ alone: no variant directory, no profiler"
RUN_TOKEN=tapAdj_ckpAll

source "$SETUP_DIR/../../../tools/lib/build_body.sh"
