#!/bin/bash
# Build the Tapenade ADJOINT. This is the one you normally want.
#   sources : code_tap/ + input_tap/  ->  build_tapAdj/mitgcmuv_tap_adj
#
# Uses STOCK genmake2: the ADJ* dump hooks are generated by Tapenade itself,
# because code_tap/forward_step.F passes the state fields to
# DUMMY_IN_STEPPING, code_tap/integr_continuity.F passes etaN to
# DUMMY_FOR_ETAN (both under ALLOW_TAPENADE), and code_tap/flow_tap_local
# declares them active; the setup's -adof file, code_tap/adjoint_tap_local,
# appends that library AFTER the stock flow_tap (Tapenade keeps the last
# declaration of an external). No generated file is post-edited. Same mechanism as
# DINO (see ../DINO_1deg/README.md, "How the Tapenade hooks work"); SOMA
# carries only the dump hooks - it has no adjViscBoost machinery to switch.
#
# SOMA's adjoint is serial-only: code_tap/SIZE.h is nPx=nPy=1 over
# sNx=sNy=62.
#
# Serial Tapenade-adjoint build for MITgcm

# Exit immediately if a command fails (-e),
# treat unset variables as errors (-u),
# and make pipelines fail if any part fails (pipefail).
set -euo pipefail

# Set root directory for MITgcm relative to THIS script (works after cd)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MITGCM_ROOT="$SCRIPT_DIR/../../MITgcm"

# Per-machine optfiles, module stack and Tapenade check. Defaults reproduce the
# sverdrup settings, so nothing changes here; on another machine add a case
# block to tools/machine_env.sh rather than editing this script.
source "$SCRIPT_DIR/../../../tools/machine_env.sh"
impacts_load_modules

# SERIAL_OPTFILE is defaulted by machine_env.sh; this catches a machine with none.
if [ -z "$SERIAL_OPTFILE" ] || [ ! -f "$SERIAL_OPTFILE" ]; then
    echo "ERROR: SERIAL_OPTFILE is unset or missing: '$SERIAL_OPTFILE'"
    echo "       Set it for machine '$MACHINE' in tools/machine_env.sh, or export it."
    exit 1
fi

# No main-program staging: code_tap/ carries no the_model_main.F, so the
# vendored model/src/the_model_main.F is compiled. (The c69f-era use_TapProfile
# switch that used to live here staged an _OG copy -- byte-identical to
# upstream -- or a _ForTapProfile one, now archived in 00_archive/code_tap/,
# and selected among patched genmake2 copies that do not exist in c69m.)
# Tapenade profiling and -nocheckpoint tuning are separate builds driven by
# -tap_extra; see tools/tapenade_profiling/README.md.

# Ensure build directory exists
if [ ! -d build_tapAdj ]; then
    echo "Creating the directory build_tapAdj..."
    mkdir build_tapAdj
fi

# Go to build directory
cd build_tapAdj || { echo "Failed to enter build_tapAdj"; exit 1; }

# Clean any previous build (ignore if Makefile not created yet)
make CLEAN || true

# Configure the build (this creates the Makefile here).
# -adof names the setup's Tapenade options file, which adds
# code_tap/flow_tap_local after the stock external library (relative paths
# resolve because genmake2 and Tapenade both run in build_tapAdj/).
"$MITGCM_ROOT/tools/genmake2" -tap \
    -rd="$MITGCM_ROOT" \
    -of="$SERIAL_OPTFILE" \
    -mods=../code_tap \
    -adof=../code_tap/adjoint_tap_local

# Generate dependency list
make depend

# Build the adjoint model using 8 threads
make -j 8 tap_adj

# Tapenade must have generated each hook's _B call, and the argument lists
# must match the hand-written routines (dump hook: 11 value/adjoint pairs +
# myTime, myIter, myThid = 25; etaN dump hook: 1 pair + 3 = 5). F77 would
# silently misalign mismatched arguments, so fail the build loudly instead.
check_gen_call() {
    local name=$1 expect=$2 file=$3 n
    n=$(awk -v pat="CALL ${name}\\\\(" '$0 ~ pat {f=1}
         f{buf=buf $0; if (index($0,")")) exit}
         END{if (buf=="") {print 0} else {print gsub(/,/,",",buf)+1}}' \
        "$file")
    if [ "${n:-0}" -ne "$expect" ]; then
        echo "ERROR: generated CALL ${name} in ${file} has ${n:-0}"
        echo "       arguments, expected ${expect}. Align the hand-written"
        echo "       routine with the generated call before using this"
        echo "       executable."
        exit 1
    fi
    echo "OK: generated ${name} call has ${expect} arguments."
}
check_gen_call DUMMY_IN_STEPPING_B 25 forward_step_b.f
check_gen_call DUMMY_FOR_ETAN_B 5 integr_continuity_b.f

# The hook adjoints must have kept their bodies. dummy_tap.F includes
# AD_CONFIG.h, the only definition of ALLOW_ADJOINT_RUN, which guards the ADJ*
# dump code: without it the adjoint is still bitwise correct but writes no ADJ*
# files (2026-09-02, runs 31071-31073). Fail here rather than after a run.
ndump=$(grep -c 'CALL DUMP_ADJ_' dummy_tap.f)
if [ "${ndump:-0}" -lt 10 ]; then
    echo "ERROR: the compiled dummy_tap.f carries only ${ndump:-0} DUMP_ADJ_* calls (expected 10):"
    echo "       the ADJ* dump bodies were preprocessed away -- check the AD_CONFIG.h include."
    exit 1
fi
echo "OK: the compiled dummy_tap.f carries ${ndump} ADJ* dump calls."
