#!/bin/bash
# Build the Tapenade ADJOINT. This is the one you normally want.
#   sources : code_tap/ + input_tap/  ->  build_tapAdj/mitgcmuv_tap_adj
#
# Uses STOCK genmake2: the ADJ* dump hook is generated by Tapenade itself,
# because code_tap/forward_step.F passes the state fields to
# TAP_DUMMY_IN_STEPPING and code_tap/flow_tap_local (injected below via
# -tap_extra) declares them active. No generated file is post-edited; the
# only DINO-specific Tapenade input is that -ext library.
#
# MPI Tapenade-adjoint build for MITgcm

# Exit immediately if a command fails (-e),
# treat unset variables as errors (-u),
# and make pipelines fail if any part fails (pipefail).
set -euo pipefail

# Set root directory for MITgcm relative to THIS script (works after cd)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MITGCM_ROOT="$SCRIPT_DIR/../../MITgcm"

# Per-machine optfiles, module stack and Tapenade check. Defaults reproduce the
# sverdrup settings, so nothing changes here; on another machine add a case
# block to tools/machine_env.sh rather than editing this script.
source "$SCRIPT_DIR/../../../tools/machine_env.sh"
impacts_load_modules

# Replace SIZE.h with mpi version
cp code_tap/SIZE.h_mpi code_tap/SIZE.h
cp code_tap/AUTODIFF_PARAMS.h_OG code_tap/AUTODIFF_PARAMS.h
cp code_tap/autodiff_readparms.F_OG code_tap/autodiff_readparms.F
cp code_tap/autodiff_inadmode_set_ad.F_OG code_tap/autodiff_inadmode_set_ad.F
cp code_tap/autodiff_inadmode_unset_ad.F_OG code_tap/autodiff_inadmode_unset_ad.F

# MPI_OPTFILE is defaulted by machine_env.sh; this catches a machine with none.
if [ -z "$MPI_OPTFILE" ] || [ ! -f "$MPI_OPTFILE" ]; then
    echo "ERROR: MPI_OPTFILE is unset or missing: '$MPI_OPTFILE'"
    echo "       Set it for machine '$MACHINE' in tools/machine_env.sh, or export it."
    exit 1
fi

###############################################
# Choose TapProfile behavior here:
#   NO    : no Tapenade profiling      -> tools/genmake2_override_forward_step_b
#   YES   : use Tapenade profiling      -> patched_ForTapProfile_genmake2    (NOT here)
#   AFTER : after acting on its advice  -> patched_AfterTapProfile_genmake2  (NOT here)
#
# Only NO works in this repository. The YES/AFTER variants keep their original
# names because that is what they are called in the one place they still exist,
# Proj_ImPACTS_old/MITgcm_c69f/MITgcm/tools/.
###############################################

use_TapProfile="NO"   # <-- change this to "YES" or "AFTER" as needed

# Decide which the_model_main.F and which patched_genmake2 to use
case "$use_TapProfile" in
    "NO")
        echo "Not Using Tapenade Profiling Tool"
        cp code_tap/the_model_main.F_OG code_tap/the_model_main.F
        GENMAKE_SCRIPT="genmake2"
        ;;

    "YES")
        echo "Using Tapenade Profiling Tool"
        cp code_tap/the_model_main.F_ForTapProfile code_tap/the_model_main.F
        GENMAKE_SCRIPT="patched_ForTapProfile_genmake2"
        ;;

    "AFTER")
        echo "Have Implemented Suggession Provided by Tapenade Profiling Tool"
        cp code_tap/the_model_main.F_OG code_tap/the_model_main.F
        GENMAKE_SCRIPT="patched_AfterTapProfile_genmake2"
        ;;

    *)
        echo "ERROR: Invalid use_TapProfile='$use_TapProfile'. Must be NO, YES, or AFTER." >&2
        exit 1
        ;;
esac

# Ensure build directory exists
if [ ! -d build_tapAdj ]; then
    echo "Creating the directory build_tapAdj..."
    mkdir build_tapAdj
fi

# Go to build directory
cd build_tapAdj || { echo "Failed to enter build_tapAdj"; exit 1; }

# Clean any previous build (ignore if Makefile not created yet)
make CLEAN || true

# Configure the build (this creates the Makefile here).
# -tap_extra passes the setup-local external library straight through to the
# Tapenade command line, alongside the stock flow_tap; it declares the
# TAP_DUMMY_IN_STEPPING hook's fields active so the ADJ* dump call is
# generated (relative path resolves because Tapenade runs in build_tapAdj/).
"$MITGCM_ROOT/tools/$GENMAKE_SCRIPT" -mpi -tap \
    -rd="$MITGCM_ROOT" \
    -of="$MPI_OPTFILE" \
    -mods=../code_tap \
    -adof="$MITGCM_ROOT/tools/adjoint_options/adjoint_tap" \
    -tap_extra "-ext ../code_tap/flow_tap_local"

# Generate dependency list
make depend

# Build the adjoint model using 8 threads
make -j 8 tap_adj

# Tapenade must have generated each hook's _B call, and the argument lists
# must match the hand-written routines (dump hook: 11 value/adjoint pairs +
# myTime, myIter, myThid = 25; mode-switch hooks: 1 pair + 3 = 5). F77 would
# silently misalign mismatched arguments, so fail the build loudly instead.
check_gen_call() {
    local name=$1 expect=$2 n
    n=$(awk -v pat="CALL ${name}\\\\(" '$0 ~ pat {f=1}
         f{buf=buf $0; if (index($0,")")) exit}
         END{if (buf=="") {print 0} else {print gsub(/,/,",",buf)+1}}' \
        forward_step_b.f)
    if [ "${n:-0}" -ne "$expect" ]; then
        echo "ERROR: generated CALL ${name} in forward_step_b.f has ${n:-0}"
        echo "       arguments, expected ${expect}. Align the hand-written"
        echo "       routine with the generated call before using this"
        echo "       executable."
        exit 1
    fi
    echo "OK: generated ${name} call has ${expect} arguments."
}
check_gen_call TAP_DUMMY_IN_STEPPING_B 25
check_gen_call TAP_INADMODE_SET_B 5
check_gen_call TAP_INADMODE_UNSET_B 5
