#!/bin/bash
# Build the Tapenade ADJOINT with EVERY call checkpointed (Tapenade's default).
#   sources : code_tap/ + input_tap/  ->  build_tapAdj_ckpAll/mitgcmuv_tap_adj
#
# This is the REFERENCE adjoint, not the default one. Since 2026-09-02 the
# default (what ./build_tapAdj.sh, a symlink, runs) is
# build_tapAdj_nocheckpoint.sh: the same adjoint with the profile-guided
# -nocheckpoint list added, bitwise identical in fc, adxx_* and ADJ* at 30 d
# and 5 yr, and 1.5x faster. Until that day this script WAS build_tapAdj.sh,
# so every run directory named tapAdj_ckpAll_* (and, before the 2026-09-02
# scratch rename, plain tapAdj_*) up to job 31055 came from it.
#
# Keep it for what -nocheckpoint cannot do: it is what the profiler build
# (build_tapAdj_tapProfile.sh) measures, since a profile of the tuned build
# would only show the residual; it is the fallback when a configuration change
# invalidates the routine list; and it is the baseline for timing comparisons.
# It is no longer needed as a correctness control -- the tuned build is
# bitwise identical to it.
#
# Uses STOCK genmake2: the ADJ* dump hook is generated by Tapenade itself,
# because code_tap/forward_step.F passes the state fields to
# TAP_DUMMY_IN_STEPPING and code_tap/flow_tap_local (injected below via
# -tap_extra) declares them active. No generated file is post-edited; the
# only DINO-specific Tapenade input is that -ext library.
#
# Pair with submit_tapAdj_ckpAll.sh.
#
# MPI Tapenade-adjoint build for MITgcm

# Exit immediately if a command fails (-e),
# treat unset variables as errors (-u),
# and make pipelines fail if any part fails (pipefail).
set -euo pipefail

# Set root directory for MITgcm relative to THIS script (works after cd)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MITGCM_ROOT="$SCRIPT_DIR/../../MITgcm"

# Per-machine optfiles, module stack and Tapenade check. Defaults reproduce the
# sverdrup settings, so nothing changes here; on another machine add a case
# block to tools/machine_env.sh rather than editing this script.
source "$SCRIPT_DIR/../../../tools/machine_env.sh"
impacts_load_modules

# Replace SIZE.h with mpi version; plain (_OG) variants
cp code_tap/SIZE.h_mpi code_tap/SIZE.h
cp code_tap/AUTODIFF_PARAMS.h_OG code_tap/AUTODIFF_PARAMS.h
cp code_tap/autodiff_readparms.F_OG code_tap/autodiff_readparms.F
cp code_tap/autodiff_inadmode_set_ad.F_OG code_tap/autodiff_inadmode_set_ad.F
cp code_tap/autodiff_inadmode_unset_ad.F_OG code_tap/autodiff_inadmode_unset_ad.F

# MPI_OPTFILE is defaulted by machine_env.sh; this catches a machine with none.
if [ -z "$MPI_OPTFILE" ] || [ ! -f "$MPI_OPTFILE" ]; then
    echo "ERROR: MPI_OPTFILE is unset or missing: '$MPI_OPTFILE'"
    echo "       Set it for machine '$MACHINE' in tools/machine_env.sh, or export it."
    exit 1
fi

# No main-program staging: code_tap/ carries no the_model_main.F, so the
# vendored model/src/the_model_main.F is compiled. (The c69f-era use_TapProfile
# switch that used to live here staged an _OG copy -- byte-identical to
# upstream -- or a _ForTapProfile one, now archived in 00_archive/code_tap/,
# and selected among patched genmake2 copies that do not exist in c69m.)
# Tapenade profiling and -nocheckpoint tuning are separate builds driven by
# -tap_extra; see tools/tapenade_profiling/README.md.

# Ensure build directory exists
if [ ! -d build_tapAdj_ckpAll ]; then
    echo "Creating the directory build_tapAdj_ckpAll..."
    mkdir build_tapAdj_ckpAll
fi

# Go to build directory
cd build_tapAdj_ckpAll || { echo "Failed to enter build_tapAdj_ckpAll"; exit 1; }

# Clean any previous build (ignore if Makefile not created yet)
make CLEAN || true

# Configure the build (this creates the Makefile here).
# -tap_extra passes the setup-local external library straight through to the
# Tapenade command line, alongside the stock flow_tap; it declares the
# TAP_DUMMY_IN_STEPPING hook's fields active so the ADJ* dump call is
# generated (relative path resolves because Tapenade runs in the build dir).
"$MITGCM_ROOT/tools/genmake2" -mpi -tap \
    -rd="$MITGCM_ROOT" \
    -of="$MPI_OPTFILE" \
    -mods=../code_tap \
    -adof="$MITGCM_ROOT/tools/adjoint_options/adjoint_tap" \
    -tap_extra "-ext ../code_tap/flow_tap_local"

# Generate dependency list
make depend

# Build the adjoint model using 8 threads
make -j 8 tap_adj

# Tapenade must have generated each hook's _B call, and the argument lists
# must match the hand-written routines (dump hook: 11 value/adjoint pairs +
# myTime, myIter, myThid = 25; etaN dump hook: 1 pair + 3 = 5; mode-switch
# hooks: 1 pair + 3 = 5). F77 would silently misalign mismatched arguments,
# so fail the build loudly instead.
check_gen_call() {
    local name=$1 expect=$2 file=$3 n
    n=$(awk -v pat="CALL ${name}\\\\(" '$0 ~ pat {f=1}
         f{buf=buf $0; if (index($0,")")) exit}
         END{if (buf=="") {print 0} else {print gsub(/,/,",",buf)+1}}' \
        "$file")
    if [ "${n:-0}" -ne "$expect" ]; then
        echo "ERROR: generated CALL ${name} in ${file} has ${n:-0}"
        echo "       arguments, expected ${expect}. Align the hand-written"
        echo "       routine with the generated call before using this"
        echo "       executable."
        exit 1
    fi
    echo "OK: generated ${name} call has ${expect} arguments."
}
check_gen_call TAP_DUMMY_IN_STEPPING_B 25 forward_step_b.f
check_gen_call TAP_INADMODE_SET_B 5 forward_step_b.f
check_gen_call TAP_INADMODE_UNSET_B 5 forward_step_b.f
check_gen_call TAP_DUMMY_FOR_ETAN_B 5 integr_continuity_b.f

# ========== BUILD RECORD ==========
# Written last, after every check above passed, so build_info.txt can only
# describe an executable this script built and verified. The submit scripts
# refuse an executable without it (or newer than it) and take run_token from
# it, so a run directory is named from what was actually built, not from what
# the submit script assumes:  DINO_1deg_<run_token>_<duration>[_<tag>]_run<jobid>
dirty=$(git -C "$SCRIPT_DIR" diff --name-only HEAD -- . \
          ':(exclude)code_tap/SIZE.h' ':(exclude)code_tap/AUTODIFF_PARAMS.h' \
          ':(exclude)code_tap/autodiff_readparms.F' \
          ':(exclude)code_tap/autodiff_inadmode_set_ad.F' \
          ':(exclude)code_tap/autodiff_inadmode_unset_ad.F' 2>/dev/null | wc -l)
{
    echo "build_script=$(basename "$(readlink -f "$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")")")"   # resolved from the setup dir: after the cd above, a relative BASH_SOURCE would not resolve the symlink
    echo "invoked_as=$(basename "${BASH_SOURCE[0]}")"
    echo "build_dir=$(basename "$PWD")"
    echo "tapenade_checkpointing=ckpAll        # every call inside a step checkpointed (Tapenade default)"
    echo "variant=OG                           # plain _OG staging, no profiler"
    echo "run_token=tapAdj_ckpAll"
    echo "tap_extra=$(sed -n 's/^TAP_EXTRA *= *//p' Makefile)"
    echo "git_commit=$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    echo "git_modified_tracked_files=${dirty}   # in this setup, build-staged files excluded"
    echo "built=$(date '+%Y-%m-%d %H:%M:%S %Z') on $(hostname)"
} > build_info.txt
echo "OK: wrote $(basename "$PWD")/build_info.txt (run_token=tapAdj_ckpAll)."
