#!/bin/bash
# Build the Tapenade ADJOINT. This is the one you normally want.
#   sources : code_tap/ + input_tap/  ->  build_tapAdj/mitgcmuv_tap_adj
#
# Uses STOCK genmake2: the ADJ* dump hooks are generated by Tapenade itself,
# because code_tap/forward_step.F passes the state fields to
# DUMMY_IN_STEPPING, code_tap/integr_continuity.F passes etaN to
# DUMMY_FOR_ETAN (both under ALLOW_TAPENADE), and code_tap/flow_tap_local
# declares them active; the setup's -adof file, code_tap/adjoint_tap_local,
# appends that library AFTER the stock flow_tap (Tapenade keeps the last
# declaration of an external). No generated file is post-edited. Same mechanism as
# DINO (see ../DINO_1deg/README.md, "How the Tapenade hooks work"); SOMA
# carries only the dump hooks - it has no adjVisc machinery to switch.
#
# Every call is checkpointed (Tapenade's default): SOMA has no checkpointing
# profile yet, so unlike DINO's build_tapAdj.sh (a symlink to its tuned
# -nocheckpoint build) this is a real file and the plain adjoint. Its run
# token is tapAdj_ckpAll, the same vocabulary as DINO, so a tuned SOMA build
# can be told apart by name when one exists.
#
# SOMA's adjoint is serial-only: code_tap/SIZE.h is nPx=nPy=1 over
# sNx=sNy=62.
#
# This file says WHAT to build; HOW is tools/lib/build_body.sh, shared by
# every build script (machine profile, genmake2, make, the generated-hook
# assertions listed in setup_params.sh, build_info.txt). Run from the setup
# directory: ./scripts/build_tapAdj.sh   Pair with submit_tapAdj.sh.

set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BUILD_DIR=build_tapAdj
BUILD_MODE=tapAdj
PARALLEL=serial
MODS=(../code_tap)
TAP_EXTRA=""
CKP=ckpAll;     CKP_NOTE="every call inside a step checkpointed (Tapenade default); SOMA has no -nocheckpoint profile yet"
VARIANT=plain;  VARIANT_NOTE="code_tap/ alone: no variant directory, no profiler"
RUN_TOKEN=tapAdj_ckpAll

source "$SETUP_DIR/../../../tools/lib/build_body.sh"
